name: Deploy to GHCR

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      release:
        description: "Release Tag"
        required: true

jobs:
  deploy:
    name: Build and Push Docker image to GHCR
    uses: ben-burwood/.actions/.github/workflows/docker-build-push.yml@main
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    with:
      dockerhub: false
